-- ============================================================
--  Amici de Gusto — Order Management System
--  Database : order_management_system
--
--  Project   : Advanced Programming Techniques Coursework
--  Institute : Informatics College Pokhara
--  Affiliation: London Metropolitan University
--
--  HOW TO USE:
--    Run this entire file in MySQL Workbench or phpMyAdmin.
--    It will drop and recreate all tables cleanly.
--    Safe to re-run — existing data will be wiped.
--
--  TABLE OVERVIEW:
--    users       — stores both customer and admin accounts
--    menu_items  — all food, drinks, and dessert items
--    orders      — one row per customer order
--    order_items — individual line items within each order
--
--  RELATIONSHIPS:
--    users  ──< orders  ──< order_items >── menu_items
--    (one user can have many orders;
--     one order can have many items;
--     each item references a menu item — nullable if deleted)
-- ============================================================


-- ── STEP 1: Create the database if it does not already exist ──────────────
CREATE DATABASE IF NOT EXISTS order_management_system
    CHARACTER SET utf8mb4          -- supports full Unicode including emojis
    COLLATE utf8mb4_unicode_ci;    -- case-insensitive Unicode comparison

-- Switch to the target database for all subsequent statements
USE order_management_system;


-- ── STEP 2: Drop existing tables in reverse dependency order ─────────────
-- Disable FK checks so we can drop tables without worrying about order
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS order_items; -- must drop before orders and menu_items
DROP TABLE IF EXISTS orders;      -- must drop before users
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS users;

-- Re-enable FK checks before creating new tables
SET FOREIGN_KEY_CHECKS = 1;


-- ============================================================
--  TABLE 1: users
--
--  Stores both regular customers (role = 'USER') and
--  admin accounts (role = 'ADMIN').
--
--  password_hash: SHA-256 hex string (64 chars, lowercase)
--    Generated by PasswordUtil.hashPassword()
--    Verified by PasswordUtil.verifyPassword()
--
--  profile_image: relative path to uploaded photo
--    e.g. /Resource/profiles/user_3_1234567890.jpg
--    NULL means no photo has been uploaded yet
-- ============================================================
CREATE TABLE users (
    id            INT           NOT NULL AUTO_INCREMENT,  -- surrogate primary key
    full_name     VARCHAR(100)  NOT NULL,                 -- display name shown in the UI
    username      VARCHAR(50)   NOT NULL,                 -- auto-generated login handle (e.g. user12345)
    email         VARCHAR(150)  NOT NULL,                 -- unique email used for login
    password_hash VARCHAR(255)  NOT NULL,                 -- SHA-256 hex of the password
    role          VARCHAR(20)   NOT NULL DEFAULT 'USER',  -- 'USER' or 'ADMIN'
    profile_image VARCHAR(500)      NULL,                 -- path to uploaded profile photo (nullable)
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP, -- account creation time

    PRIMARY KEY (id),
    UNIQUE KEY uq_users_username (username), -- prevents duplicate usernames
    UNIQUE KEY uq_users_email    (email)     -- prevents duplicate email addresses
);


-- ============================================================
--  TABLE 2: menu_items
--
--  All items available on the restaurant menu.
--  Managed by the admin through the Menu Management panel.
--
--  category: must be one of 'food', 'drinks', 'dessert'
--    (enforced by the application layer, not a DB constraint)
--
--  image_url: relative path to the item's photo
--    e.g. /Resource/menu/item_1234567890.jpg
--    NULL or default.jpg means no custom image has been set
-- ============================================================
CREATE TABLE menu_items (
    id          INT            NOT NULL AUTO_INCREMENT,  -- surrogate primary key
    name        VARCHAR(150)   NOT NULL,                 -- item name shown on the menu
    category    VARCHAR(50)    NOT NULL,                 -- 'food', 'drinks', or 'dessert'
    price       DECIMAL(10,2)  NOT NULL,                 -- price in NPR (e.g. 850.00)
    description TEXT               NULL,                 -- short description shown on the menu card
    image_url   VARCHAR(500)       NULL,                 -- path to item image (nullable)
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP, -- when the item was added

    PRIMARY KEY (id)
);


-- ============================================================
--  TABLE 3: orders
--
--  One row per order placed by a customer.
--  The token shown to the customer is derived from the ID:
--    ADG-00001, ADG-00002, etc. (formatted in Java)
--
--  status lifecycle:
--    PENDING (default when order is placed)
--    COMPLETED (set by admin from the Order Management panel)
--
--  payment_status:
--    UNPAID (default) → PAID (set by admin via Billing page)
--
--  ON DELETE CASCADE: deleting a user removes all their orders
-- ============================================================
CREATE TABLE orders (
    id             INT            NOT NULL AUTO_INCREMENT,         -- surrogate primary key
    user_id        INT            NOT NULL,                        -- FK → users.id (who placed the order)
    status         VARCHAR(30)    NOT NULL DEFAULT 'PENDING',      -- 'PENDING' or 'COMPLETED'
    payment_status VARCHAR(20)    NOT NULL DEFAULT 'UNPAID',       -- billing status
    total_price    DECIMAL(10,2)  NOT NULL,                        -- total amount in NPR
    special_note   TEXT               NULL,                        -- optional note from the customer
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP, -- when the order was placed

    PRIMARY KEY (id),

    -- Deleting a user cascades to remove all their orders
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);


-- ============================================================
--  TABLE 4: order_items
--
--  Each row is one line item (one product) inside an order.
--
--  WHY item_name and item_price are snapshots:
--    If an admin later edits or deletes a menu item, the
--    original receipt must still show the correct name and price.
--    So we copy the values at the moment the order is placed.
--
--  menu_item_id is nullable:
--    Set to NULL if the referenced menu item is deleted later.
--    ON DELETE SET NULL preserves order history.
--
--  ON DELETE CASCADE on order_id:
--    Deleting an order removes all its line items.
-- ============================================================
CREATE TABLE order_items (
    id           INT            NOT NULL AUTO_INCREMENT,  -- surrogate primary key
    order_id     INT            NOT NULL,                 -- FK → orders.id (which order this belongs to)
    menu_item_id INT                NULL,                 -- FK → menu_items.id (nullable if item deleted)
    item_name    VARCHAR(150)   NOT NULL,                 -- snapshot of item name at order time
    item_price   DECIMAL(10,2)  NOT NULL,                 -- snapshot of item price at order time (NPR)
    quantity     INT            NOT NULL DEFAULT 1,       -- how many of this item were ordered

    PRIMARY KEY (id),

    -- Deleting an order cascades to remove all its line items
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id)
        ON DELETE CASCADE,

    -- If a menu item is deleted, set this FK to NULL (keeps order history intact)
    CONSTRAINT fk_order_items_menu
        FOREIGN KEY (menu_item_id) REFERENCES menu_items (id)
        ON DELETE SET NULL
);


-- ============================================================
--  SEED DATA: default admin account
--
--  Username : admin
--  Password : admin123
--  Hash     : SHA-256 hex of "admin123"
--
--  To verify or generate a hash in MySQL:
--    SELECT LOWER(SHA2('yourpassword', 256));
-- ============================================================
INSERT INTO users (full_name, username, email, password_hash, role) VALUES
(
    'Administrator',
    'admin',
    'admin@amicidegusto.com',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', -- SHA-256 of 'admin123'
    'ADMIN'
);


-- ============================================================
--  SEED DATA: sample menu items
--  Images default to /Resource/default.jpg until real photos
--  are uploaded through the admin Menu Management panel.
-- ============================================================
INSERT INTO menu_items (name, category, price, description, image_url) VALUES

-- ── Food ──────────────────────────────────────────────────
('Margherita Pizza',    'food',    850.00,
 'Classic tomato base, fresh mozzarella and basil',
 '/Resource/default.jpg'),

('Spaghetti Carbonara', 'food',    950.00,
 'Creamy egg sauce, pancetta, parmesan, black pepper',
 '/Resource/default.jpg'),

('Penne Arrabbiata',    'food',    800.00,
 'Spicy tomato sauce, garlic, fresh chilli',
 '/Resource/default.jpg'),

('Lasagna al Forno',    'food',   1050.00,
 'Layers of pasta, beef ragu, bechamel, parmesan',
 '/Resource/default.jpg'),

('Risotto ai Funghi',   'food',    900.00,
 'Arborio rice, wild mushrooms, white wine, parmesan',
 '/Resource/default.jpg'),

-- ── Drinks ────────────────────────────────────────────────
('Espresso',            'drinks',  150.00,
 'Single shot of rich Italian espresso',
 '/Resource/default.jpg'),

('Cappuccino',          'drinks',  200.00,
 'Espresso with steamed milk foam',
 '/Resource/default.jpg'),

('Sparkling Water',     'drinks',  120.00,
 'Chilled sparkling mineral water 500ml',
 '/Resource/default.jpg'),

('Fresh Lemonade',      'drinks',  250.00,
 'Freshly squeezed lemon, mint, soda',
 '/Resource/default.jpg'),

-- ── Dessert ───────────────────────────────────────────────
('Tiramisu',            'dessert', 450.00,
 'Classic Italian dessert with mascarpone and espresso',
 '/Resource/default.jpg'),

('Panna Cotta',         'dessert', 380.00,
 'Vanilla cream with berry coulis',
 '/Resource/default.jpg'),

('Cannoli',             'dessert', 350.00,
 'Crispy pastry shells filled with sweet ricotta',
 '/Resource/default.jpg');
